
[[constraint]]
  branch = "master"
  name = "github.com/GeertJohan/go-sourcepath"

[[constraint]]
  name = "github.com/Unknwon/com"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/acarl005/stripansi"

[[constraint]]
  branch = "master"
  name = "github.com/cevaris/ordered_map"

[[constraint]]
  name = "github.com/cheggaaa/pb"
  version = "2.0.6"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  name = "github.com/fatih/structs"
  version = "1.1.0"

[[constraint]]
  name = "github.com/getlantern/deepcopy"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-python/gpython"
  branch = "master"

[[constraint]]
  name = "github.com/google/go-cmp"
  version = "0.2.0"

[[constraint]]
  name = "github.com/jaypipes/ghw"
  version = "0.1.0"

[[constraint]]
  name = "github.com/k0kubun/pp"
  version = "2.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/leekchan/gtf"

[[constraint]]
  branch = "master"
  name = "github.com/linkosmos/mapop"

[[constraint]]
  name = "github.com/lucasb-eyer/go-colorful"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/mailru/easyjson"

[[constraint]]
  branch = "master"
  name = "github.com/mattn/go-zglob"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/mitchellh/hashstructure"
  version = "1.0.0"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  version = "1.1.2"

[[constraint]]
  branch = "master"
  name = "github.com/muesli/gamut"

[[constraint]]
  name = "github.com/olekukonko/tablewriter"
  version = "0.0.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/rai-project/archive"

[[constraint]]
  branch = "master"
  name = "github.com/rai-project/config"

[[constraint]]
  branch = "master"
  name = "github.com/rai-project/logger"

[[constraint]]
  branch = "master"
  name = "github.com/rai-project/nvidia-smi"

[[constraint]]
  branch = "master"
  name = "github.com/rai-project/onnx"

[[constraint]]
  branch = "master"
  name = "github.com/rai-project/utils"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/spf13/cast"
  version = "1.3.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/tensorflow/tensorflow"
  version = "1.11.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"

[[constraint]]
  branch = "master"
  name = "gonum.org/v1/gonum"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/alecthomas/chroma"

[[constraint]]
  branch = "master"
  name = "github.com/alecthomas/repr"
